"""Provider-neutral production planning contracts."""

from .providers import (
    CostQuote,
    CostUnit,
    GenerationNeed,
    MediaGenerationProvider,
    ProductionRecord,
    PrototypeStage,
    ProviderCapability,
    ProviderCommitmentRequest,
    ProviderDescriptor,
    StabilityEvaluation,
    StabilityPolicy,
    authorize_provider_commitment,
    evaluate_stability,
    provider_can_satisfy,
)

__all__ = [
    "CostQuote",
    "CostUnit",
    "GenerationNeed",
    "MediaGenerationProvider",
    "ProductionRecord",
    "PrototypeStage",
    "ProviderCapability",
    "ProviderCommitmentRequest",
    "ProviderDescriptor",
    "StabilityEvaluation",
    "StabilityPolicy",
    "authorize_provider_commitment",
    "evaluate_stability",
    "provider_can_satisfy",
]


from .contracts import (
    GenerationAuthorization,
    GenerationScope,
    KeyframeRecord,
    LockedReference,
    ProviderSnapshot,
    PublicationMethod,
    PublicationReceipt,
    QCStatus,
    SceneCard,
    SocialObservation,
    VideoPrototypeRecord,
    require_authorized_quote,
)
from .stage3 import (
    CostBucket,
    PreflightResult,
    ProviderSummary,
    Stage3Evaluation,
    Stage3Phase,
    build_provider_summaries,
    build_repeatability_records,
    evaluate_keyframe_preflight,
    evaluate_stage3,
    evaluate_video_preflight,
    keyframe_is_complete,
    stage3_report_dict,
    summarize_costs,
    video_is_complete,
)

__all__ += [
    "GenerationAuthorization",
    "GenerationScope",
    "KeyframeRecord",
    "LockedReference",
    "ProviderSnapshot",
    "PublicationMethod",
    "PublicationReceipt",
    "QCStatus",
    "SceneCard",
    "SocialObservation",
    "VideoPrototypeRecord",
    "require_authorized_quote",
    "CostBucket",
    "PreflightResult",
    "ProviderSummary",
    "Stage3Evaluation",
    "Stage3Phase",
    "build_provider_summaries",
    "build_repeatability_records",
    "evaluate_keyframe_preflight",
    "evaluate_stage3",
    "evaluate_video_preflight",
    "keyframe_is_complete",
    "stage3_report_dict",
    "summarize_costs",
    "video_is_complete",
]


from .higgsfield_api import (
    HIGGSFIELD_API_PROVIDER_ID,
    HiggsfieldApiGenerationRequest,
    HiggsfieldApiSubmission,
    extract_first_media_url,
    load_official_higgsfield_client,
    submit_generation,
    upload_reference,
    wait_for_result,
)
from .launch import (
    LaunchProject,
    LaunchReview,
    LaunchShot,
    LaunchShotResult,
    LaunchStatus,
    approve_for_publication,
    prepare_human_review,
)

__all__ += [
    "HIGGSFIELD_API_PROVIDER_ID",
    "HiggsfieldApiGenerationRequest",
    "HiggsfieldApiSubmission",
    "extract_first_media_url",
    "load_official_higgsfield_client",
    "submit_generation",
    "upload_reference",
    "wait_for_result",
    "LaunchProject",
    "LaunchReview",
    "LaunchShot",
    "LaunchShotResult",
    "LaunchStatus",
    "approve_for_publication",
    "prepare_human_review",
]
